package com.mylinehub.crm.whatsapp.enums;

public enum CurrencyCode {
    AED("784", "United Arab Emirates dirham"),
    AFN("971", "Afghan afghani"),
    ALL("008", "Albanian lek"),
    AMD("051", "Armenian dram"),
    AOA("973", "Angolan kwanza"),
    ARS("032", "Argentine peso"),
    AUD("036", "Australian dollar"),
    AWG("533", "Aruban florin"),
    AZN("944", "Azerbaijani manat"),
    BAM("977", "Bosnia and Herzegovina convertible mark"),
    BBD("052", "Barbados dollar"),
    BDT("050", "Bangladeshi taka"),
    BGN("975", "Bulgarian lev"),
    BHD("048", "Bahraini dinar"),
    BIF("108", "Burundian franc"),
    BMD("060", "Bermudian dollar"),
    BND("096", "Brunei dollar"),
    BOB("068", "Bolivian boliviano"),
    BOV("984", "Bolivian Mvdol (funds code)"),
    BRL("986", "Brazilian real"),
    BSD("044", "Bahamian dollar"),
    BTN("064", "Bhutanese ngultrum"),
    BWP("072", "Botswana pula"),
    BYN("933", "Belarusian ruble"),
    BZD("084", "Belize dollar"),
    CAD("124", "Canadian dollar"),
    CDF("976", "Congolese franc"),
    CHF("756", "Swiss franc"),
    CLP("152", "Chilean peso"),
    CNY("156", "Chinese yuan"),
    COP("170", "Colombian peso"),
    CRC("188", "Costa Rican colón"),
    CUC("192", "Cuban convertible peso"),
    CUP("192", "Cuban peso"),
    CVE("132", "Cape Verde escudo"),
    CZK("203", "Czech koruna"),
    DJF("262", "Djiboutian franc"),
    DKK("208", "Danish krone"),
    DOP("214", "Dominican peso"),
    DZD("012", "Algerian dinar"),
    EGP("818", "Egyptian pound"),
    ERN("232", "Eritrean nakfa"),
    ETB("230", "Ethiopian birr"),
    EUR("978", "Euro"),
    FJD("242", "Fijian dollar"),
    FKP("238", "Falkland Islands pound"),
    GBP("826", "Pound sterling"),
    GEL("981", "Georgian lari"),
    GHS("936", "Ghanaian cedi"),
    GIP("292", "Gibraltar pound"),
    GMD("270", "Gambian dalasi"),
    GNF("324", "Guinean franc"),
    GTQ("320", "Guatemalan quetzal"),
    GYD("328", "Guyanese dollar"),
    HKD("344", "Hong Kong dollar"),
    HNL("340", "Honduran lempira"),
    HTG("332", "Haitian gourde"),
    HUF("348", "Hungarian forint"),
    IDR("360", "Indonesian rupiah"),
    ILS("376", "Israeli new shekel"),
    INR("356", "Indian rupee"),
    IQD("368", "Iraqi dinar"),
    IRR("364", "Iranian rial"),
    ISK("352", "Icelandic króna"),
    JMD("388", "Jamaican dollar"),
    JOD("400", "Jordanian dinar"),
    JPY("392", "Japanese yen"),
    KES("404", "Kenyan shilling"),
    KGS("417", "Kyrgyzstani som"),
    KHR("116", "Cambodian riel"),
    KMF("174", "Comorian franc"),
    KPW("408", "North Korean won"),
    KRW("410", "South Korean won"),
    KWD("414", "Kuwaiti dinar"),
    KYD("136", "Cayman Islands dollar"),
    KZT("398", "Kazakhstani tenge"),
    LAK("418", "Lao kip"),
    LBP("422", "Lebanese pound"),
    LKR("144", "Sri Lankan rupee"),
    LRD("430", "Liberian dollar"),
    LSL("426", "Lesotho loti"),
    LYD("434", "Libyan dinar"),
    MAD("504", "Moroccan dirham"),
    MDL("498", "Moldovan leu"),
    MGA("969", "Malagasy ariary"),
    MKD("807", "Macedonian denar"),
    MMK("104", "Myanmar kyat"),
    MNT("496", "Mongolian tugrik"),
    MOP("508", "Macanese pataca"),
    MRO("478", "Mauritanian ouguiya"),
    MUR("480", "Mauritian rupee"),
    MVR("462", "Maldivian rufiyaa"),
    MWK("454", "Malawian kwacha"),
    MXN("484", "Mexican peso"),
    MYR("458", "Malaysian ringgit"),
    MZN("943", "Mozambican metical"),
    NAD("516", "Namibian dollar"),
    NGN("566", "Nigerian naira"),
    NIO("558", "Nicaraguan córdoba"),
    NOK("578", "Norwegian krone"),
    NPR("524", "Nepalese rupee"),
    NZD("554", "New Zealand dollar"),
    OMR("512", "Omani rial"),
    PAB("590", "Panamanian balboa"),
    PEN("604", "Peruvian nuevo sol"),
    PGK("598", "Papua New Guinean kina"),
    PHP("608", "Philippine peso"),
    PKR("586", "Pakistani rupee"),
    PLN("985", "Polish złoty"),
    PYG("600", "Paraguayan guarani"),
    QAR("634", "Qatari riyal"),
    RON("946", "Romanian leu"),
    RSD("941", "Serbian dinar"),
    RUB("643", "Russian ruble"),
    RWF("646", "Rwandan franc"),
    SAR("682", "Saudi riyal"),
    SBD("090", "Solomon Islands dollar"),
    SCR("690", "Seychellois rupee"),
    SDG("938", "Sudanese pound"),
    SEK("752", "Swedish krona"),
    SGD("702", "Singapore dollar"),
    SHP("654", "Saint Helena pound"),
    SLL("694", "Sierra Leonean leone"),
    SOS("706", "Somali shilling"),
    SPL("736", "Seborga luigino"),
    SRD("740", "Surinamese dollar"),
    STD("678", "São Tomé and Príncipe dobra"),
    SVC("222", "Salvadoran colón"),
    SYP("760", "Syrian pound"),
    SZL("748", "Swazi lilangeni"),
    THB("764", "Thai baht"),
    TJS("972", "Tajikistani somoni"),
    TMT("795", "Turkmenistani manat"),
    TND("788", "Tunisian dinar"),
    TOP("776", "Tongan paʻanga"),
    TRY("949", "Turkish lira"),
    TTD("780", "Trinidad and Tobago dollar"),
    TVD("798", "Tuvaluan dollar"),
    TWD("901", "New Taiwan dollar"),
    TZS("834", "Tanzanian shilling"),
    UAH("980", "Ukrainian hryvnia"),
    UGX("800", "Ugandan shilling"),
    USD("840", "United States dollar"),
    UYU("858", "Uruguayan peso"),
    UZS("860", "Uzbekistani soʻm"),
    VEF("937", "Venezuelan bolívar"),
    VND("704", "Vietnamese đồng"),
    VUV("548", "Vanuatu vatu"),
    WST("882", "Samoan tālā"),
    XAF("950", "CFA franc BEAC"),
    XCD("951", "East Caribbean dollar"),
    XDR("960", "Special drawing rights"),
    XOF("952", "CFA franc BCEAO"),
    XPF("953", "CFP franc"),
    YER("886", "Yemeni rial"),
    ZAR("710", "South African rand"),
    ZMW("967", "Zambian kwacha"),
    ZWD("716", "Zimbabwe dollar");

    private final String numericCode;
    private final String currencyName;

    CurrencyCode(String numericCode, String currencyName) {
        this.numericCode = numericCode;
        this.currencyName = currencyName;
    }

    public String getNumericCode() {
        return numericCode;
    }

    public String getCurrencyName() {
        return currencyName;
    }
}