package com.mylinehub.crm.enums;


public enum ASTERISK_EVENTS {
	ContactStatusEvent,
	NewChannelEvent,
	VarSetEvent,
	NewExtenEvent,
	NewStateEvent,
	DeviceStateChangeEvent,
	HangupEvent,
	CdrEvent,
	NewConnectedLineEvent,
	MusicOnHoldStopEvent,
	BridgeEnterEvent,
	BridgeEvent,
	ConfbridgeJoinEvent,
	MeetMeJoinEvent,
	RtcpReceivedEvent,
	RtcpSentEvent,
	ConfbridgeLeaveEvent,
	MeetMeLeaveEvent,
	BridgeLeaveEvent,
	MusicOnHoldStartEvent,
	SoftHangupRequestEvent,
	HangupRequestEvent,
	ExtensionStatusEvent,
	ConfbridgeEndEvent,
	MeetMeEndEvent,
	BridgeDestroyEvent,
	FullyBootedEvent,
	ConnectEvent,
	PeerStatusEvent,
	DisconnectEvent,
	QueueMemberStatusEvent,
	AgentCompleteEvent,
	ChannelUpdateEvent,
	ChannelReloadEvent,
	ChannelTalkingStartEvent,
	ChannelTalkingStopEvent
}