package com.mylinehub.crm.enums;

//Usage in campaignservice
//
public enum AUTODIALER_TYPE {
//        PRIDICTIVE_DIALER,IVR_DIALER
	     AI_CALL,WHATSAPP_MESSAGE,PROGRESSIVE_DIALER,PRIDICTIVE_DIALER,PREVIEW_DIALER,QUEUE_DIALER,IVR_DIALER,YOUTUBE_DIALER,CONFERENCE_DIALING, RATIO_DIALING,HARD_STICKY_DIALING,SOFT_STICKY_DIALING;
}

