package com.mylinehub.crm.entity;


import java.time.Instant;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@NoArgsConstructor
@ToString
@Entity
@Table(name = "supportticket",
indexes = {
		  @Index(name = "supportticket_Organization_Index", columnList = "organization"),
		  @Index(name = "supportticket_customerId_Index", columnList = "customerId"),
		  @Index(name = "supportticket_open_Index", columnList = "open"),
		})
public class SupportTicket {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "supportticket_sequence"
    )
    @SequenceGenerator(
            name="supportticket_sequence",
            sequenceName = "supportticket_sequence",
            allocationSize = 1,
            initialValue = 100
    )
    @Column(nullable = false)
    private Long id;
    //This string is generated by function in Util package
    private String complaintId;
    private Long customerId;

    private  boolean open;
    private  String organization;
    private String productOrServiceName;
    private String customerEmailId;
    private String complaint;
    
    @Column(updatable = false)
    @CreationTimestamp
    private Instant createdOn;
    
    @UpdateTimestamp
    private Instant lastUpdatedOn;
    
}
